### PR TITLE
Fix : issue #2

### LINKED ISSUE #2: [Feature] Footer Section
This site should I have a Footer section .

**Why Footer Section should be there ? -:**

1 .Navigation and Site Map: The footer provides easy navigation and a site map, helping users find information quickly.

2. Contact Information: Display important contact details like phone numbers, email addresses, and social media links.

3. Additional Links and Resources: Showcase related links, partners, and important pages that don't fit in the main navigation.

4. Copyright and Legal Information: Include copyright notices, disclaimers, and terms of service to protect intellectual property and ensure compliance.

**Requirements - :**
1.Your Social media links .

I will make a good Footer section for your website .

### PR DESCRIPTION
**Pull request by parthpathakpp1**
I made a Footer section for the website . 

https://github.com/Deveimer/vovoca-frontend/assets/85991449/8808a2b2-956f-4589-be2c-649b129f789a

### CODE REVIEW

**Comment by varun-singhh** [comment]
1. Resolve conflicts.
2. Where is contact us form which meant to be present at the bottom.

**Comment by parthpathakpp1** [comment]
> 1. Resolve conflicts.
> 2. Where is contact us form which meant to be present at the bottom.

1. Resolved the conflicts 
2. Contact us form is there only above Footer section . Contact us form folder was previously named Footer then I changed it to Contact as I had to make Footer section . 


https://github.com/Deveimer/vovoca-frontend/assets/85991449/e54d850e-6815-4df6-ad0e-9ffcc91d47a6

**Comment by varun-singhh** [comment]
We have changes in get in touch section, firstly we will merge those changes and then will suggest few alignment fixes in here then you can fix those to get it merged.

If you want to work on that issue comment on issue #54 to get it assigned.

**Comment by parthpathakpp1** [comment]
> We have changes in get in touch section, firstly we will merge those changes and then will suggest few alignment fixes in here then you can fix those to get it merged.
> 
> If you want to work on that issue comment on issue #54 to get it assigned.

Commented . You mean to say after merging newsletter changes . you will merge this Footer section ? right ?

**Comment by parthpathakpp1** [comment]
@varun-singhh can I work on issue #54 or after getting assigned?????

**Comment by varun-singhh** [comment]
> @varun-singhh can I work on issue #54 or after getting assigned?????

already assigned you #54

**Comment by parthpathakpp1** [comment]
> > @varun-singhh can I work on issue #54 or after getting assigned?????
> 
> already assigned you #54

ok

**Pull request closed without merging**
