### PR TITLE
Login Button Updated Design

### LINKED ISSUE #18: "Login" Button Design Improvement
The design of the "Login" button is nice but the underline effect is not looking good and somehow making the user think of purpose of this effect. By removing or modifying its design, the button will look even better.

I want to work on this improvement as a part of GSSOC-23.

### PR DESCRIPTION
**Pull request by iamRabia-N**
This PR contains the code of updated Login button design. 
The issue related to this PR is:
**"Login" Button Design Improvement #18**

### CODE REVIEW

**Comment by varun-singhh** [comment]
@iamRabia-N attach before and after screen shots

**Comment by iamRabia-N** [comment]
### Design BEFORE changes
vovoca ss (2)

### Design AFTER changes
vovoca ss (1)

**Review by varun-singhh — APPROVED** [review]

**Comment by iamRabia-N** [comment]
@varun-singhh kindly assign level to this pull request

**Comment by iamRabia-N** [comment]
@varun-singhh Kindly mention the level

**Comment by iamRabia-N** [comment]
@kaustubhai Kindly add level in this merged PR

**Pull request merged**
