### PR TITLE
New branch for testimonial section

### PR DESCRIPTION
**Pull request by Pragati-3003**
I have updated the UI of the testimonial section .
issues #14

### CODE REVIEW

**Comment by kaustubhai** [comment]
Yo, the changes LGTM but please change your commit message. Your commit message should convey what changes you are making. To change it please follow this
1. Make sure you are in the correct branch
2. `git reset HEAD~`
3. `git add ./styles/Testimonial.module.css`
4. `git commit -m <NEW_AND_DETAILED_MESSAGE>`
5. `git push origin Pragati-3003:vovoca-14-2`

**Comment by kaustubhai** [comment]
Please tag me once done, will approve it

**Comment by Pragati-3003** [comment]
> Please tag me once done, will approve it

Hey!!
@kaustubhai ,I have changed the commit message , please check.

**Review by kaustubhai — APPROVED** [review]

**Comment by kaustubhai** [comment]
LGTM @varun-singhh

**Review by varun-singhh — APPROVED** [review]

**Pull request merged**
